name: Build for Linux ARM
on:
  workflow_dispatch:

env:
  APP_NAME: "Sample Desktop App"

jobs:
  build-arm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        run: echo "hello world"
